
export  const USER_LOGGED_IN_SUCCESS = "USER_LOGGED_IN_SUCCESS";
export  const USER_LOGGED_IN_FAILED = "USER_LOGGED_IN_FAILED";

export  const SET_EMAIL_PROPERTIES = "SET_EMAIL_PROPERTIES";
export  const SET_EMAIL_HTML = "SET_EMAIL_HTML";
export  const SET_INPUT_CHECK = "SET_INPUT_CHECK";


